require("odas0r.config.lazy")
require("odas0r.lib.reload")
require("odas0r.config.options")
require("odas0r.config.filetypes")
require("odas0r.config.autocmds")
require("odas0r.config.keymaps")
require("odas0r.config.commands")
require("odas0r.features")
