# Environment Variables
[env]
TERM = "alacritty"
# WINIT_X11_SCALE_FACTOR="1.0"

[shell]
args = ["--cd ~"]
program = "wsl.exe"

# Window Configuration
[window]
opacity = 1
dynamic_padding = false
decorations = "Full"
padding = { x = 8, y = 8 }


# Font Configuration
[font]
size = 12.0
normal = { family = "JetBrains Mono", style = "Medium" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Medium Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

# Scrolling
[scrolling]
history = 10000
multiplier = 3

[terminal]
# osc52 = "CopyPaste"

# Colors (Gruvbox dark)

# Primary Colors
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"
bright_foreground = "#fbf1c7"
dim_foreground = "#a89984"

# Cursor Colors
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

# Vi Mode Cursor Colors
[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

# Selection Colors
[colors.selection]
text = "CellBackground"
background = "CellForeground"

# Bright Colors
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"

blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

# Normal Colors
[colors.normal]
black = "#282828"  # Gruvbox dark background
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

# Dim Colors
[colors.dim]
black = "#32302f"
red = "#9d0006"
green = "#79740e"
yellow = "#b57614"
blue = "#076678"
magenta = "#8f3f71"
cyan = "#427b58"
white = "#928374"


# Keybindings
[keyboard]
bindings = [
    { key = "T", mods = "Control", command = { program = "alacritty" } },
    { key = "C", mods = "Control", chars = "\u0003"},
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste"},
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp", mode = "~Alt" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown", mode = "~Alt" },
    { key = "Home", mods = "Shift", action = "ScrollToTop", mode = "~Alt" },
    { key = "End", mods = "Shift", action = "ScrollToBottom", mode = "~Alt" },
]
