#!/usr/bin/env bash

set -euo pipefail

if [[ -n "$WSL_DISTRO_NAME" ]]; then
  mkdir -p "/mnt/c/Users/Guilherme Rosado/AppData/Roaming/alacritty"
  rm "/mnt/c/Users/Guilherme Rosado/AppData/Roaming/alacritty/alacritty.toml"
  cp "$DOT/alacritty/alacritty.toml" "/mnt/c/Users/Guilherme Rosado/AppData/Roaming/alacritty/alacritty.toml"
fi

ln -sf "$DOT/alacritty/alacritty.toml" "$HOME/.alacritty.toml"

printf "Alacritty setup done! 🌟\n"
