#!/usr/bin/env bash

set -e

# install custom scripts
mkdir -p "$HOME/.local/bin"
ln -sf "$HOME/dot/scripts" "$HOME/.local/bin/scripts"

ln -sf "$HOME/dot/bashrc" "$HOME/.bashrc"
ln -sf "$HOME/dot/inputrc" "$HOME/.inputrc"
ln -sf "$HOME/dot/bash" "$HOME/.bash"

# MacOS shit
if [[ $OSTYPE == "darwin"* ]]; then
  ln -sf "karabiner.json" "$HOME/.config/karabiner/karabiner.json"
  ln -sf "tabnine_config.json" "/Users/odas0r/Library/Preferences/TabNine/tabnine_config.json"
fi

printf "Executing all setup scripts ✨...\n"

readarray -d '' folders < <(
  find "$HOME/dot" -mindepth 1 -maxdepth 1 -type d \
    -not -path "$HOME/dot/.git"
)

for path in $folders; do
  cd "$path"
  [[ -f "./setup" ]] && ./setup
  cd - >/dev/null || exit 1
done
