#!/usr/bin/env bash

set -e

if [[ ! -x "$(command -v gh)" ]]; then
  echo "gh isn't installed, skipping..." >&2
  exit 1
fi

DOT_GH="$HOME/github.com/odas0r/gh"

# create gh config directory
mkdir -p "$HOME/.config/gh"

# create the symlink to the config
if [[ $OSTYPE == "darwin"* ]]; then
  ln -sf "$DOT_GH/config.darwin.yml" "$HOME/.config/gh/config.yml"
else
  ln -sf "$DOT_GH/config.yml" "$HOME/.config/gh/config.yml"
fi

echo "Don't forget to: gh auth login"

printf "Gh setup done! 🌟\n"
