#!/usr/bin/env bash

set -euo pipefail

# create gh config directory
mkdir -p "$HOME/.config/gh"

# create the symlink to the config
ln -sf "$DOT/gh/config.yml" "$HOME/.config/gh/config.yml"

printf "Gh setup done! 🌟\n"
