#!/bin/bash

set -e

if [ ! -x "$(command -v vim)" ]; then
  echo Need to install full vim.
  exit 1
fi

# Setup Vim
ln -sf "$PWD/vimrc" "$HOME/.vimrc"

echo Do not forget to :PlugInstall!
echo "Vim setup done! 🌟"
