#!/bin/sh

if [ -z "$(which vim)" -o -z "$(which vimtutor)" ]; then
  echo Need to install full vim.
  exit 1
fi

# Setup Vim
ln -sf "$PWD/vimrc" "$HOME/.vimrc"

echo Do not forget to :PlugInstall!
echo "Vim setup done! 🌟\n"
