#!/usr/bin/env bash

echo -e "\n[odas0r]: Cloning all projects...\n"

cd "$HOME/github.com/odas0r"

git clone git@github.com:Odas0R/dot.git &
git clone git@github.com:Odas0R/portfolio.git &
git clone git@github.com:Odas0R/zet-cmd.git &
git clone git@github.com:Odas0R/nr-cmd.git &
git clone git@github.com:Odas0R/neon-noir.git &
git clone git@github.com:Odas0R/zet.git &
git clone git@github.com:Odas0R/supabase-starter.git &

wait
