#!/usr/bin/env bash

if [[ ! -x "$(command -v lazygit)" ]]; then
  echo "You need to install lazygit"
  exit 1
fi


if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS OSX
  ln -sf "$HOME/dot/lazygit/config.yml" "$HOME/Library/Application Support/lazygit/config.yml"
else
  ln -sf "$HOME/dot/lazygit/config.yml" "$HOME/.config/lazygit/config.yml"
fi
