#!/usr/bin/env bash

set -euo pipefail

NVIM="$HOME/.config/nvim"

# creates the nvim config directory
mkdir -p "$NVIM"

# setups
ln -sf "$DOT/nvim/init.lua" "$NVIM/init.lua"
ln -sf "$DOT/nvim/spell" "$NVIM/spell"

# setup lua and plugins
ln -sf "$DOT/nvim/after" "$NVIM"
ln -sf "$DOT/nvim/lua" "$NVIM"
ln -sf "$DOT/nvim/plugin" "$NVIM"

echo "Neovim setup done! 🌟"
