#!/bin/bash

set -e

if [ ! -x "$(command -v nvim)" ]; then
  echo Need to install full neovim.
  echo Check /dot/installs
  exit 1
fi

NVIM="$HOME/.config/nvim/"

# creates the nvim config directory
mkdir -p "$NVIM"

# setups
ln -sf "$PWD/init.vim" "$NVIM/init.vim"
ln -sf "$PWD/spell" "$NVIM/spell"
ln -sf "$PWD/coc-settings.json" "$NVIM/coc-settings.json"

# installing plug
curl -fLo "$NVIM/autoload/plug.vim" --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo Do not forget to :PlugInstall!
echo "Vim setup done! 🌟"
