#!/usr/bin/env bash

set -e

if [ ! -x "$(command -v nvim)" ]; then
  echo "Need to install neovim" >&2
  exit 1
fi

DOT_NVIM="$HOME/github.com/odas0r/dot/nvim"
NVIM="$HOME/.config/nvim"

# creates the nvim config directory
mkdir -p "$NVIM"

# setups
ln -sf "$DOT_NVIM/init.vim" "$NVIM/init.vim"
ln -sf "$DOT_NVIM/spell" "$NVIM/spell"

# setup snippets
mkdir -p "$HOME/snippets"
ln -sf "$DOT_NVIM/ultisnips" "$HOME/snippets/ultisnips"

# setup lua and plugins
ln -sf "$DOT_NVIM/lua" "$NVIM"
ln -sf "$DOT_NVIM/plugin" "$NVIM"

# installing plug
if [[ ! -f "$NVIM/autoload/plug.vim" ]]; then
  curl -fLo "$NVIM/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

printf "To install all vim plugins :PlugInstall!\n"

echo "Neovim setup done! 🌟"
