#!/usr/bin/env bash

set -e

VERSION=0.18.2

mkdir /tmp/bat-install && cd /tmp/bat-install

curl -OL https:/github.com/sharkdp/bat/releases/download/v${VERSION}/bat_${VERSION}_amd64.deb

sudo dpkg -i bat_0.18.2_amd64.deb
