#!/usr/bin/env bash

set -euo pipefail

cd "$(mktemp -d)"

wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64

chmod +x cloudflared-linux-amd64

mv cloudflared-linux-amd64 "$HOME/.local/bin/cloudflared"
