#!/usr/bin/env bash

set -euo pipefail

cd /tmp

# clone the installer
git clone https://github.com/eradman/entr
cd entr

# run configure
/tmp/entr/configure
# run tests
make test

# install entr
sudo make install
