#!/usr/bin/env bash

set -e

if [[ $OSTYPE == "darwin"* ]]; then
  brew install fzf
  # To install useful key bindings and fuzzy completion:
  $(brew --prefix)/opt/fzf/install
else
  # install with github
  git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
  $HOME/.fzf/install
fi
