#!/usr/bin/env bash

set -euo pipefail

# if [[ ! -x "$(command -v gh)" ]]; then
#   curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
#   echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
# fi

# Upgrade
sudo apt install gh

# Extensions
gh extension install github/gh-copilot
