#!/usr/bin/env bash

set -e

if [[ ! -x "$(command -v go)" ]]; then
  echo "you need to instal golang!"
  echo "check dot/install/golang"
  exit 1
fi

curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
