#!/usr/bin/env bash

set -e

version="v4.15.2"
platform="linux"

mkdir -p /tmp/migrate
cd /tmp/migrate

# download the migrate binary
curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$platform-amd64.tar.gz | tar xvz 

# install the migrate binary
sudo install migrate /usr/local/bin
