#!/bin/sh

set -e

version=$(curl https://go.dev/VERSION?m=text)
echo "VERSION: $version"

os="linux"
arch="amd64"
tarFile="${version}.${os}-${arch}.tar.gz"
url="https://golang.org/dl/${tarFile}"

# Download the latest golang
wget --continue --show-progress "${url}"
printf "Downloaded Golang!\n"

# Remove the old golang
sudo rm -rf /usr/local/go

# Install the new Go
sudo tar -C /usr/local -xzf "$tarFile"
printf "Create the skeleton for your local users go directory\n"
mkdir -p ~/go
mkdir -p ~/go/bin
mkdir -p ~/go/pkg
mkdir -p ~/go/src

# GoPath
printf "Don't forget to add these:\n"
echo "export GOPATH=~/go"
echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'

# Installing Golang Dependencies
# TODO: Add dependencies?

# Remove Download
sudo rm "$tarFile"

# Print Go Version
/usr/local/go/bin/go version
