#!/bin/sh

set -e

full_version=$(curl -s https://go.dev/VERSION?m=text)
version=$(echo $full_version | grep -o 'go[0-9.]*')

os="linux"
arch="amd64"
tarFile="${version}.${os}-${arch}.tar.gz"
url="https://go.dev/dl/${tarFile}"

# Download the latest golang
wget --continue --show-progress "${url}"
printf "Downloaded Golang!\n"

# Remove the old golang
sudo rm -rf /usr/local/go

# Install the new Go
sudo tar -C /usr/local -xzf "$tarFile"
printf "Create the skeleton for your local users go directory\n"
mkdir -p "$HOME/go/bin"
mkdir -p "$HOME/go/pkg"
mkdir -p "$HOME/go/src"

# GoPath
printf "Don't forget to add these:\n"
echo "export GOPATH=~/go"
echo 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'

# Remove Download
sudo rm "$tarFile"

# Print Go Version
/usr/local/go/bin/go version

########################################
# Golang Dependencies, Tools
########################################

go install golang.org/x/tools/gopls@latest
go install golang.org/x/tools/cmd/goimports@latest
go install golang.org/x/tools/cmd/gorename@latest
go install golang.org/x/tools/cmd/godoc@latest
