#!/usr/bin/env bash

set -euo pipefail

# https://github.com/jesseduffield/lazygit?tab=readme-ov-file#ubuntu

tmpdir=$(mktemp -d)

cd "$tmpdir"

LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
sudo install lazygit /usr/local/bin
