#!/usr/bin/env bash

set -euo pipefail

cd /tmp && mkdir -p litestream

cd litestream


wget https://github.com/benbjohnson/litestream/releases/download/v0.3.13/litestream-v0.3.13-linux-amd64.deb
sudo dpkg -i litestream-v0.3.13-linux-amd64.deb
rm litestream-v0.3.13-linux-amd64.deb

