#!/usr/bin/env bash

set -euo pipefail

sudo apt install build-essential libreadline-dev unzip

cd /tmp/

# Check versions here https://www.lua.org/ftp
#
LUA_VERSION=5.1.5
if [[ -d "lua-$LUA_VERSION" ]]; then
  rm -rf "lua-$LUA_VERSION"
fi

curl -O "https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz"
tar zxf "lua-$LUA_VERSION.tar.gz"
cd "lua-$LUA_VERSION"
make linux test
sudo make install

LUA_ROCKS_VERSION=3.11.0
if [[ -d "luarocks-$LUA_ROCKS_VERSION" ]]; then
  rm -rf "luarocks-$LUA_ROCKS_VERSION"
fi
curl -O "https://luarocks.github.io/luarocks/releases/luarocks-$LUA_ROCKS_VERSION.tar.gz"
tar zxf "luarocks-$LUA_ROCKS_VERSION.tar.gz"
cd "luarocks-$LUA_ROCKS_VERSION"
./configure --with-lua-include=/usr/local/include
make
sudo make install
