#!/usr/bin/env bash

set -e

# Docs: https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(Standalone)

if [[ -d "$HOME/tools/lua-language-server" ]]; then
  rm -rf "$HOME/tools/lua-language-server"
fi

mkdir -p $HOME/tools/
cd $HOME/tools
git clone --depth=1 https://github.com/sumneko/lua-language-server 

cd lua-language-server
git submodule update --init --recursive

# build on Linux
cd 3rd/luamake
compile/install.sh
cd ../..
./3rd/luamake/luamake rebuild
