#!/usr/bin/env bash

set -e

# Docs: https://luals.github.io/wiki/build/

if [[ -d "$HOME/tools/lua-language-server" ]]; then
  rm -rf "$HOME/tools/lua-language-server"
fi

mkdir -p $HOME/tools/
cd $HOME/tools
git clone --depth=1 https://github.com/sumneko/lua-language-server
./make.sh
