#!/usr/bin/env bash

set -euo pipefail

cd /tmp/

VERSION="2023-12-09"

curl -L "https://github.com/artempyanykh/marksman/releases/download/${VERSION}/marksman-linux-x64" -o marksman

chmod +x marksman

mv marksman $HOME/.local/bin/
