#!/usr/bin/env bash

set -e

# install nvim on osx

if [[ $OSTYPE == "darwin"* ]]; then
  brew install --HEAD luajit
  brew install --HEAD neovim
  exit 0
fi

# install nvim on debian

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
mv nvim.appimage nvim
chmod u+x ./nvim

sudo mv ./nvim /usr/bin

# install nvr

sudo apt install python3-pip
pip3 install neovim-remote
