#!/usr/bin/env bash

set -e

read -r -p "Prefer nightly? [y/Y]" answer
if [[ $answer =~ [yY](es)* ]]; then
  curl -LJO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
else
  curl -LJO https://github.com/neovim/neovim/releases/download/latest/nvim.appimage
fi

mv nvim.appimage nvim
chmod u+x ./nvim

sudo mv ./nvim /usr/bin

# install nvr

sudo apt install python3-pip
pip3 install neovim-remote
