#!/usr/bin/env bash

set -euo pipefail

# Dependencies
sudo apt-get install -y ninja-build gettext libtool libtool-bin autoconf \
  automake cmake g++ pkg-config unzip

cd /tmp

rm -rf neovim

git clone https://github.com/neovim/neovim

git -C neovim checkout 5c36701

cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo

sudo make install

echo "Done! Run 'nvim' to start neovim."
echo "nvim is installed at $(which nvim)"
