#!/usr/bin/env bash

set -euo pipefail

# https://docs.opencv.org/4.x/d7/d9f/tutorial_linux_install.html

cd /tmp/

# Install minimal prerequisites (Ubuntu 18.04 as reference)
sudo apt update && sudo apt install -y cmake g++ wget unzip
 
# Download and unpack sources
wget -O opencv.zip https://github.com/opencv/opencv/archive/4.9.0.zip
unzip opencv.zip
 
# Create build directory
mkdir -p build && cd build
 
# Configure
cmake ../opencv-4.9.0
 
# Build
cmake --build .
