#!/usr/bin/env bash

set -e

# get the latest version of stripe cli (tag_name)
owner="stripe"
repo="stripe-cli"

version="$(curl --silent "https://api.github.com/repos/${owner}/${repo}/releases/latest" | grep "tag_name" | cut -d ":" -f2- | cut -d '"' -f 2)"
package="stripe_${version//v/}_linux_x86_64.tar.gz"

mkdir -p /tmp/stripe-install
cd /tmp/stripe-install

# download the latest release
wget "https://github.com/stripe/stripe-cli/releases/download/${version}/${package}"

# tar the file
tar -xvf "$package"
chmod u+x ./stripe

# Put the new stripe cli on the /usr/bin to be globally available
sudo mv ./stripe /usr/bin
