#!/usr/bin/env bash

# create installer dir
mkdir -p /tmp/stylua-installer
cd /tmp/stylua-installer

# download and install binary
VERSION=v0.13.0
wget "https://github.com/JohnnyMorganz/StyLua/releases/download/$VERSION/stylua-linux.zip"
unzip stylua-linux.zip
sudo install stylua /usr/local/bin

# cleanup
cd - && rm -rf /tmp/stylua-installer
