#!/usr/bin/env bash

rm -rf /tmp/tmux

git clone https://github.com/tmux/tmux.git /tmp/tmux

cd /tmp/tmux  || exit 1

git checkout 3.3a

sh autogen.sh

./configure && make

sudo make install

cd - || exit 1

rm -fr /tmp/tmux
