#!/usr/bin/env bash

rm -rf /tmp/tmux

git clone https://github.com/tmux/tmux.git /tmp/tmux

cd /tmp/tmux

git checkout 3.3

sh autogen.sh

./configure && make

sudo make install

cd -

rm -fr /tmp/tmux
