#!/usr/bin/env bash

set -e

#####################################
# Install via NPM
#####################################
if [[ ! -x "$(command -v npm)" ]]; then
  echo "You need to install npm"
  exit 1
fi

# check all pacakges globally: npm list -g --depth=0
npm install -g \
  yarn \
  typescript \
  prettier \
  prettier-plugin-toml \
  prettier-plugin-astro \
  prettier-plugin-tailwindcss \
  @go-task/cli \
  wrangler

#####################################
# Installed via APT
#####################################

sudo apt install \
  shellcheck \
  ripgrep

#####################################
# Installed via PIP
#####################################
if [[ ! -x "$(command -v pip)" ]]; then
  echo "You need to install pip"
  exit 1
fi

pip install \
  'python-lsp-server[all]' \
  gitlint

#####################################
# Installed via Go
#####################################
if [[ ! -x "$(command -v go)" ]]; then
  echo "You need to install go"
  exit 1
fi

go install \
  github.com/jesseduffield/lazydocker@latest \
  github.com/mattn/efm-langserver@latest \
  mvdan.cc/sh/v3/cmd/shfmt@latest \
  github.com/jesseduffield/lazygit@latest \
  github.com/mattn/efm-langserver@latest
