#!/usr/bin/env bash

# https://software.opensuse.org/download.html?project=home%3Ajustkidding&package=ueberzugpp

# Install dependencies
# accept the installation of the packages
sudo apt-get install libssl-dev libvips-dev libsixel-dev libchafa-dev libtbb-dev

# sudo apt install libx11-dev libxinerama-dev libxft-dev libx11-xcb-dev libxcb-res0-dev
# sudo apt install libxcb*-dev
# sudo apt install libopencv-dev

cd $HOME

if [[ -d "ueberzugpp" ]]; then
  git -C ueberzugpp pull
else
  git clone https://github.com/jstkdng/ueberzugpp.git
fi


cd ueberzugpp
git checkout master
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WAYLAND=ON  ..
cmake --build .
install ueberzug $HOME/.local/bin
install ueberzugpp $HOME/.local/bin
