#!/bin/sh

# config vim -> opens vim on ~/.vimrc
# config bash -> opens vim on ~/.bashrc

CONFIGS=~/dot
COMMANDS="vim bash gh git aliases tmux"

case $1 in
-h | --help)
  printf "usage: config <config>\n"
  printf "Available: ${COMMANDS}\n\n"
  exit 0
  ;;
vim)
  exec code $CONFIGS/vim/vimrc
  exit 0
  ;;
bash)
  exec code $CONFIGS/bashrc
  exit 0
  ;;
gh)
  exec code $CONFIGS/gh/config.yml
  exit 0
  ;;
git)
  exec code ~/.gitconfig
  exit 0
  ;;
aliases)
  exec code $CONFIGS/bash/aliases.sh
  exit 0
  ;;
tmux)
  exec code $HOME/.tmux.conf
  exit 0
  ;;
complete)
  exec code $HOME/.bash/complete.sh
  exit 0
  ;;
--bash-completion)
  printf "$COMMANDS"
  exit 0
  ;;
edit)
  exec code $CONFIGS/scripts/config
  exit 0
  ;;
esac

printf "usage: config <config>\n"
printf "Available: ${COMMANDS}\n\n"
