#!/bin/sh

# config vi -> opens vi on ~/.virc
# config bash -> opens vi on ~/.bashrc

CONFIGS=~/dot
COMMANDS="vi bash gh git alias tmux terminal"

case $1 in
-h | --help)
  printf "usage: config <config>\n"
  printf "Available: ${COMMANDS}\n\n"
  exit 0
  ;;
vi)
  exec vi $CONFIGS/vim/vimrc
  exit 0
  ;;
bash)
  exec vi $CONFIGS/bashrc
  exit 0
  ;;
gh)
  exec vi $CONFIGS/gh/config.yml
  exit 0
  ;;
git)
  exec vi ~/.gitconfig
  exit 0
  ;;
alias)
  exec vi $CONFIGS/bash/aliases.sh
  exit 0
  ;;
tmux)
  exec vi $HOME/.tmux.conf
  exit 0
  ;;
complete)
  exec vi $HOME/.bash/complete.sh
  exit 0
  ;;
--bash-completion)
  printf "$COMMANDS"
  exit 0
  ;;
terminal)
  exec vi $CONFIGS/windows-terminal/settings.json
  ;;
esac

printf "usage: config <config>\n"
printf "Available: ${COMMANDS}\n\n"
