#!/bin/bash

set -e

currentDate=$(date +"%Y-%m-%d")
file="${HOME}/zet/journal/${currentDate}.md"

if [ -f "$file" ]; then
  vim "$file"
else

  # Append the daily template on the file
  tee "$file" <<EOF >/dev/null
# Journal Entry, ${currentDate}

*Work so hard you want to quit every day.*
*Be so hard you never fucking quit.*


EOF

  # Open the daily file
  vi +6 "$file"
fi
