#!/usr/bin/env bash

set -e

if [[ -n $1 ]]; then
  # find the files by regex & open them w/ nvim
  find "$DOT" -type f -name "*$1*" -exec nvim '{}' +
  exit 0
fi

file=$(
  fd . "$DOT" | fzf --multi \
    --prompt="Search through your dotfiles > " \
    --preview 'bat --theme=gruvbox-dark --style=numbers --color=always {}'
)

if [[ -f $file ]]; then
  if [[ ${file: -4} =~ (.png|jpeg|gif) ]]; then
    open "${file}"
    exit 0
  else
    nvim "${file}"
  fi
fi
