#!/bin/bash

set -e

if [[ -n "$1" ]]; then
  # find the files by regex & open them w/ vim
  find "$HOME/dot" -type f -name "*$1*" -exec vim '{}' +
  exit 1
fi

cd "$HOME/dot"
file="$(fzf --preview 'bat --style=numbers --color=always {}')"

if [[ -f "$file" ]]; then
  if [[ "${file: -4}" =~ (.png|jpeg|gif) ]]; then
    cd "$(dirname "$file")"
    open "$(basename "$file")"
    exit 1
  else
    vim "$file"
  fi
fi
