#!/usr/bin/env bash

set -e

if [[ ! -x "$(command -v fzf-tmux)" ]]; then
  echo "You need to install fzf-tmux"
  exit 1
fi

if [[ ! -x "$(command -v fd)" ]]; then
  echo "You need to install fd"
  exit 1
fi

if [[ -n $1 ]]; then
  # find the files by regex & open them w/ vim
  find "$HOME/dot" -type f -name "*$1*" -exec nvimr '{}' +
  exit 0
fi

cd "$DOT"

file=$(
  fzf-tmux -p 95% --multi \
    --prompt="Search through your dotfiles > " \
    --preview 'bat --theme=gruvbox-dark --style=numbers --color=always {}'
)

if [[ -f $file ]]; then
  if [[ ${file: -4} =~ (.png|jpeg|gif) ]]; then
    cd "$(dirname "$file")"
    open "$(basename "$file")"
    exit 0
  else
    nvimr "$file"
  fi
fi
