#!/usr/bin/env bash

set -euo pipefail

emulator=$(emulator -list-avds | gum choose --header="Choose an emulator to start")

if [[ -z "${emulator}" ]]; then
  exit 0
fi

# restart the server
adb kill-server
adb start-server

emulator -avd "${emulator}" -gpu host -no-boot-anim -no-audio
