#!/usr/bin/env bash

set -euo pipefail

GUM="go run github.com/charmbracelet/gum@v0.14.1"

emulator=$(emulator -list-avds | $GUM choose --header="Choose an emulator to start")

if [[ -z "${emulator}" ]]; then
  exit 0
fi

# restart the server
adb kill-server
adb start-server

emulator -avd "${emulator}" -gpu host -no-boot-anim -no-audio
