#!/usr/bin/env bash

set -euo pipefail

# check if there's args, if not list all available emulators
if [[ -z "${*}" ]]; then
  echo "No arguments provided, listing all available emulators"
  emulator -list-avds
  exit 0
fi

# restart the server
adb kill-server
adb start-server

emulator -avd "$@"
