#!/bin/sh

args=$(printf '%s\n' "$@")

showPreview() {
  [ -z "$args" ] && args="main"
  preview="git diff $args --color=always -- {-1}"
  git diff "$args" --name-only | fzf -m --ansi --preview "$preview"
}

if git rev-parse --git-dir >/dev/null 2>&1; then
  [ -d .git ] && showPreview >/dev/null
else
  echo "Error: Not inside a git repository."
fi
