#!/usr/bin/env bash

set -euo pipefail

file="$1"

if [[ -z "$file" ]]; then
  echo "Usage: $0 <file>"
  exit 1
fi

if [[ ! -f "$file" ]]; then
  echo "File not found: $file"
  exit 1
fi

# check if gist exists with the filename already and if so, update it
# otherwise, create a new gist
gist=$(gh gist list | grep "$(basename "$file")")

if [[ -n "$gist" ]]; then
  echo "Updating gist: $file"
  gist_id=$(echo "$gist" | awk '{print $1}')
  gh gist edit "$gist_id" --add "$file"
  exit 0
else
  echo "Create new gist? (y/n)"
  read -r answer
  if [[ "$answer" == "y" ]]; then
    gh gist create "$file" --web
    exit 0
  fi
fi
