#!/usr/bin/env bash

set -e

if [[ ! -d "$1" ]]; then
  echo "the given path isn't a directory"
  exit 1
fi

cd "$1"

if ! git rev-parse HEAD >/dev/null 2>&1; then
  echo "the given path isn't a github repo"
  exit 1
fi

function sync() {
  # Check if there are uncommitted changes
  if [ -n "$(git status --porcelain)" ]; then
    git add .
    git commit -m "automated/scripted commit and push " -q
    git pull -q
    git push -q
  fi
}

# run the command on the background
(sync &) &>/dev/null
