#!/bin/sh

# This is a very simple automated add, commit, push that is run when you
# open a mark by using `ws` if there's local changes that weren't
# committed yet

syncRepos="dot zet"

# Iterate through the repos to be sync
sync() {
  for repo in $syncRepos; do
    # Check if repo exists
    if [ ! -h "$MARKPATH/$repo" ]; then
      echo "repo ${repo} does not exist, fix it."
      exit
    fi

    # CD into the repo from the symlink
    cd -P "$MARKPATH/$repo" || return

    # Check if there are changes in the current repo
    if [ -n "$(git status --porcelain)" ]; then
      git add . && git commit -m "automated from gitsync... 🎉" -q && git push -q
      # Go back
      # cd -
    fi
  done
}

# Run the command on the background, always
(sync &) &>/dev/null
