#!/usr/bin/env bash

set -e

HTTPIE="$HOME/httpie"

print_help() {
  printf "
httpx, a simple api query management program that relies on HTTPie.

Commands:
  help             Show help commands
  new              Create a new query file
  query            Search for all the queries

"
}

new_query() {
  name="$1"
  file="${HTTPIE}/${name}.$(isosec).sh"

  if [[ -z "$name" ]]; then
    echo "invalid arguments: name"
    exit 1
  fi

  tee "$file" <<EOF >/dev/null
#!/usr/bin/env bash

# DELETE THIS IF NOT NEEDED
#
# a few examples to follow
#
# get a user from the api
# http pie.dev/user
#
# give it a header and json body
# http PUT pie.dev/put X-API-Token:123 name=John
#
# create a user
# http POST pie.dev/put name=John email=john@example.org
#
# submitting forms
# http -f POST pie.dev/post hello=World
#
# upload a file using redirected ouput
# http pie.dev/post < files/data.json
#
# set a cookie
# http pie.dev/cookies Cookie:sessionid=foo


EOF
  nvim +25 "$file"
}

query() {
  cd "$HTTPIE"
  file=$(fd | fzf --preview 'bat --theme='gruvbox-dark' --color=always {}')
  [[ -n "$file" ]] && nvim "$file"
}

case "$1" in
help)
  print_help
  exit 0
  ;;
"")
  print_help
  exit 0
  ;;
n | new)
  new_query "${@:2}"
  exit 0
  ;;
q | query)
  query "${@:2}"
  exit 0
  ;;
esac
