#!/usr/bin/env bash

set -euo pipefail

version="$1"

# validate version semver format
if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid version format. Please use semver format (e.g., 1.24.2)."
  exit 1
fi

/usr/local/go/bin/go install "golang.org/dl/go${version}@latest"
go${version} download
