#!/usr/bin/env bash

declare INSTALLS_PATH="$HOME/github.com/odas0r/dot/install"

# Generate a list of installer scripts
installer_scripts=$(find "$INSTALLS_PATH" -mindepth 1 -maxdepth 1 -type f -printf "%p\n" |
  fzf-tmux -p 40% --multi --prompt="Your installers > ")

# Run the selected installer scripts
for script in $installer_scripts; do
  echo "Running $script"
  bash "$script"
done
