#!/usr/bin/env bash

npm install -g \
  prettier \
  gemini \
  aws-static-deploy \
  bash-language-server \
  fixjson \
  typescript-language-server \
  vscode-css-language-server \
  vscode-html-language-server \
  vscode-json-language-server \
  vscode-markdown-language-server \
  @astrojs/language-server \
  yml-language-server

# go install golang.org/x/tools/gopls@latest
# go install golang.org/x/tools/cmd/goimports@latest
# go install golang.org/x/tools/cmd/gorename@latest
# go install golang.org/x/tools/cmd/godoc@latest
