#!/usr/bin/env bash

declare INSTALLS_PATH="$HOME/github.com/odas0r/dot/install"

# Generate a list of installer scripts
installer_scripts=$(fd --type f --maxdepth 1 . "$INSTALLS_PATH" |
  fzf --multi --prompt="Your installers > ")

# Run the selected installer scripts
for script in $installer_scripts; do
  echo "Running $script"
  bash "$script"
done
