#!/usr/bin/env bash

npm install -g \
  prettier \
  @google/gemini-cli@latest \
  @mypolis.eu/aws-static-deploy \
  bash-language-server \
  fixjson \
  typescript-language-server \
	vscode-langservers-extracted \
  @astrojs/language-server \
  yaml-language-server

# go install golang.org/x/tools/gopls@latest
# go install golang.org/x/tools/cmd/goimports@latest
# go install golang.org/x/tools/cmd/gorename@latest
# go install golang.org/x/tools/cmd/godoc@latest
