#!/usr/bin/env bash

npm install -g \
  bash-language-server \
  typescript \
  typescript-language-server \
  vscode-langservers-extracted \
  @astrojs/language-server \
  yaml-language-server

# go install golang.org/x/tools/gopls@latest
# go install golang.org/x/tools/cmd/goimports@latest
# go install golang.org/x/tools/cmd/gorename@latest
# go install golang.org/x/tools/cmd/godoc@latest
