#!/usr/bin/env bash

set -euo pipefail

# WARNING: This is a dirty fix for a bug on neovim, maybe will crash in the
# future.
#
# 2>&1 redirects stderr (file descriptor 2) to stdout (file descriptor 1), so any
# output sent to stderr by the nvim command will be captured into the currentPath
# variable.
if [[ ! -S "$NVIM_SOCKET" ]] || [[ ! -f "$HOME/.nvim-buf" ]]; then
  lazygit "$@"
  exit 0
fi

currentBufferPath="$(cat "$HOME/.nvim-buf")"
dirPath="$(dirname "$currentBufferPath")"

cd "$dirPath" || exit 1

topDir=$(git rev-parse --show-toplevel 2>/dev/null)
lazygit --path "$topDir" "$@"
