#!/usr/bin/env bash

set -e

if [[ ! -x "$(command -v lazydocker)" ]]; then
  echo "You need to install lazydocker"
  exit 1
fi

found="$(find . -regex "\./docker-compose\.ya?ml")"

if [[ -f $found ]]; then 
  popup lazydocker -c "$found" "$@"
else
  popup lazydocker "$@"
fi

