#!/usr/bin/env bash

if [[ ! -x "$(command -v lazygit)" ]]; then
  echo "You need to install lazygit"
  exit 1
fi

nvimBuf="$(cat "$HOME/.nvim-buf")"
nvimBufDirPath="$(dirname "$nvimBuf")"
cd "$nvimBufDirPath" || exit 1
dir=$(git rev-parse --show-toplevel 2>/dev/null)
lazygit -p "$dir" "$@"
