#!/usr/bin/env bash

[[ -z ${1} ]] && echo "usage: newx <name>" && exit 1

path="$HOME/.local/bin/scripts/${1}"

if [[ -e $path ]]; then
  read -r -p "${1} already exists. Edit?" yes
  case "$yes" in
  y | yes | ok | okay) nvim "$path" ;;
  esac
  exit 0
fi

tee "$path" <<EOF >/dev/null
#!/usr/bin/env bash

set -euo pipefail

EOF

chmod +x "$path"
nvim "$path"
