#!/usr/bin/env bash

set -e

declare -r ZET="$HOME/github.com/zet"
declare -r JOURNAL="$ZET/journal"
declare -r DAILY_TEMPLATE="$ZET/.templates/daily.tmpl.md"

declare nextdayDate

if [[ $OSTYPE == "darwin"* ]]; then
  nextdayDate=$(gdate --date="next day" "+%Y-%m-%d")
else
  nextdayDate=$(date --date="next day" "+%Y-%m-%d")
fi

file="$JOURNAL/${nextdayDate}.md"

if [[ ! -f "$file" ]]; then
  # Append the daily template on the file
  export title="# Journal Entry, ${nextdayDate}"
  tmpl "$DAILY_TEMPLATE" >"$file"

  popup nvim "$file"
else
  popup nvim "$file"
fi
