#!/bin/sh

file="${1}.md"
path="$HOME/notes/${file}"

[ ! -n "${1}" ] && echo "usage: note <name> '<title>'" && exit 1;

if [ -f "${path}" ]; then
  read -p "${1} already exists. Edit? " yes
  case "${yes}" in
    y|yes|ok|okay) exec vim "${path}"
  esac
  exit 0
fi

printf "# ${2}\n\n\n" > "${path}"
exec vim +3 "${path}"
