#!/usr/bin/env bash

set -e

if [[ ! -S "$NVIM_SOCKET" ]]; then
  nvim --listen "$NVIM_SOCKET" "$@"
else
  # if we're on lazygit, we need to send the file to the correct buffer
  filePath="$(realpath "$1")"
  nvim --server "$NVIM_SOCKET" --remote-send "<C-\><C-N>:wincmd p | e ${filePath}<CR>"
fi
