#!/usr/bin/env bash

set -e

if [[ -z "$TMUX" ]]; then
  nvim "$@"
fi

if [[ ! -S "$NVIM_SOCKET" ]]; then
  nvim --listen "$NVIM_SOCKET" "$@"
else
  filePath="$(realpath "$1")"
  nvim --server "$NVIM_SOCKET" --remote-send "<C-\><C-N>:wincmd p | e ${filePath}<CR>"
fi
