#!/usr/bin/env bash

set -euo pipefail

if [ -z "${1:-}" ]; then
  echo "Usage: $0 <path to test file>"
  exit 1
elif [ ! -f "$1" ]; then
  echo "File not found: $1"
  exit 1
fi

nvim --headless -c "PlenaryBustedFile ${1}"
