#!/usr/bin/env bash

if [[ ! -x "$(command -v pg_format)" ]]; then
  echo "You need to install pg_format"
  exit 1
fi

LANG=C pg_format \
  --tabs \
  --spaces 2 \
  --keyword-case 2 \
  --no-extra-line
