#!/usr/bin/env bash

if [[ ! -x "$(command -v pg_format)" ]]; then
  echo "You need to install pg_format"
  exit 1
fi

LANG=C pg_format \
  --spaces 2 \
  --comma-start \
  --keyword-case 1 \
  --wrap-comment \
  --wrap-limit 78 \
  --nogrouping \
  --no-extra-line
