#!/usr/bin/env bash

set -e

NVIM="$HOME/.config/nvim/lua/odas0r"

if [[ -n $1 ]]; then
  # find the files by regex & open them w/ vim
  DOT="$HOME/dot/nvim/lua/odas0r"
  find "$DOT" -type f -name "*efm*" | xargs basename | xargs -I{} nvim "$NVIM/{}"
  exit 0
fi

cd "$NVIM"
file="$(fzf --preview 'bat --theme='gruvbox-dark'  --style=numbers --color=always {}')"
nvim "$file"
