#!/usr/bin/env bash

set -e

if [[ ! -x "$(command -v tmux)" ]]; then
  echo "You need to install tmux"
  exit 1
fi

# check if tmux is already running
if [[ -n "$TMUX" ]]; then
  tmux popup -h90% -w95% -E "$@"
else
  echo "Popup requires tmux to be running..."
  "$@"
fi

