#!/usr/bin/env bash

set -e

declare -r ZET="$HOME/github.com/zet"
declare -r JOURNAL="$ZET/journal"
declare -r DAILY_TEMPLATE="$ZET/.templates/daily.tmpl.md"

declare yesterdaysDate

if [[ $OSTYPE == "darwin"* ]]; then
  yesterdaysDate=$(gdate --date="yesterday" "+%Y-%m-%d")
else
  yesterdaysDate=$(date --date="yesterday" "+%Y-%m-%d")
fi

file="$JOURNAL/${yesterdaysDate}.md"

if [[ ! -f $file ]]; then

  # create a new journal using the `tmpl` script
  export title="# Journal Entry, ${yesterdaysDate}"
  tmpl "$DAILY_TEMPLATE" >"$file"

  # Open the daily file
  popup nvim "$file"
else
  popup nvim "$file"
fi
