#!/usr/bin/env bash

declare -r ZET="$HOME/github.com/zet"
declare -r JOURNAL="$ZET/journal"

yesterdayDate=:

if [[ $OSTYPE == "darwin"* ]]; then
  yesterdayDate=$(gdate --date="yesterday" "+%Y-%m-%d")
else
  yesterdayDate=$(date --date="yesterday" "+%Y-%m-%d")
fi

file="$JOURNAL/${yesterdayDate}.md"

if [[ ! -f $file ]]; then
  # Append the daily template on the file
  tee "$file" <<EOF >/dev/null
# Journal Entry, ${yesterdayDate}

EOF

  # Append the daily.md
  cat "$ZET/daily.md" >>"$file"

  # Open the daily file
  popup nvim +2 "$file"
else
  popup nvim "$file"
fi
