#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: <padding> <inner_radius>"
  exit 1
fi

if ! [[ $1 =~ ^[0-9]+$ ]] || ! [[ $2 =~ ^[0-9]+$ ]]; then
  echo "Error: Please provide valid numbers"
  exit 1
fi

padding=$1
inner_radius=$2
border_radius=$((padding + inner_radius))
echo "Outer Radius: border-radius: ${border_radius}px;"
