#!/bin/sh

# Take it this way:
#
# Retrieving information using active recall helps you remember it.
# It’s much better than simply recognizing an answer, re-reading
# information, note-taking, or concept mapping.

file="${RECALLPATH}/${1}.md"
recallList=$(find $RECALLPATH -maxdepth 1 -iname "*.md" -exec sh -c 'for f
do basename -- "$f" .md;done' sh {} +)

if [ ! -n "${1}" ]; then
  echo "usage: recall <topic>\n"
  echo "Available:"
  echo $recallList
  return
fi

if [ ! -f "${file}" ]; then
  read -p "Do you want to recall ${1}? [Y/y]" yes
  case "${yes}" in
  y | Y) echo "# ${2}\n\n" >"${file}" && exec vim $file ;;
  esac
  exit 0
else
  exec vi $file
fi
