#!/usr/bin/env bash

#!/usr/bin/env bash

if command -v glab &>/dev/null; then
  glab repo view --web
elif command -v gh &>/dev/null; then
  gh repo view --web
else
  echo "Neither GitHub CLI nor GitLab CLI found"
  exit 1
fi
