#!/usr/bin/env bash

set -euo pipefail

#
# Run any command on any repository of choosing
#

declare GITHUB_PATH="$HOME/github.com"
declare RR_COMMANDS_PATH="$HOME/github.com/odas0r/dot/.rr-commands"
declare RR_HISTORY_PATH="$HOME/github.com/dot/.rr"

if [[ ! -x "$(command -v lazygit)" ]]; then
  echo "You need to install lazygit"
  exit 1
fi

if [[ ! -x "$(command -v fzf-tmux)" ]]; then
  echo "You need to install fzf-tmux"
  exit 1
fi

_append_command_to_history() {
  sed '1 s/^/$\n/'
}

repo=$(
  find "$GITHUB_PATH" -mindepth 2 -maxdepth 2 -type d |
    fzf-tmux -p 40% --prompt="Your repositories > "
)

cd "$repo" || exit 1

readarray -t lines < <(fzf-tmux -p 40% --print-query --prompt="Run > " <"$RR_COMMANDS_PATH")

query="${lines[0]}"
if [[ -n "$query" ]]; then
  eval "$query" 

  # append command to the history of commands

  exit 0
fi

selected="${lines[1]}"
if [[ -n "$selected" ]]; then
  eval "$selected" 
  exit 0
fi
