#!/bin/sh

[ ! -n "${1}" ] && exec tmux && exit 0

case $1 in
-h | --help)
  echo "Session is a tmux wrapper tool for better readability...\n"
  echo "usage: session [ new | rename | kill | ls | -h | --help ] session_id\n"
  exit 0
  ;;
ls)
  echo "Sessions Available:\n"
  sessions=$(exec tmux ls)
  echo "${sessions}\n"
  exit 0
  ;;
new)
  exec tmux new-session -s $2
  exit 0
  ;;
rename)
  exec tmux rename-session -t $2 $3
  exit 0
  ;;
kill)
  exec tmux kill-session -t $2 $3
  exit 0
  ;;
esac

# If no args like rename, kill, attach
exec tmux attach -t $1
