#!/bin/sh

[ -z "$1" ] && exec tmux && exit 0

case $1 in
-h | --help)
  printf "Session is a tmux wrapper tool for better readability...\n"
  printf "usage: session [ new | rename | kill | ls | -h | --help ] session_id\n"
  exit 0
  ;;
ls)
  printf "Sessions Available:\n"
  sessions=$(exec tmux ls)
  printf "%s\n" "$sessions"
  exit 0
  ;;
new)
  exec tmux new-session -s "$2"
  exit 0
  ;;
rename)
  exec tmux rename-session -t "$2" "$3"
  exit 0
  ;;
kill)
  exec tmux kill-session -t "$2"
  exit 0
  ;;
esac

# If no args like rename, kill, attach
exec tmux attach -t "$1"
