#!/usr/bin/env bash

set -euo pipefail

DISTRO=:

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  DISTRO=$(awk -F= '/^NAME/{print ${2}}' /etc/os-release)

  if [[ ${DISTRO} = "Ubuntu"* ]]; then
    if uname -a | grep -q '^Linux.*Microsoft'; then
      # ubuntu via WSL Windows Subsystem for Linux
      iconv -t ascii//TRANSLIT | sed -r s/[~'^']+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr "[:upper:]" "[:lower:]"
    else
      # native ubuntu
      echo "NOT IMPLEMENTED"
    fi
  elif [[ ${DISTRO} = "Debian"* ]]; then
    # debian
    echo "NOT IMPLEMENTED"
  fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS OSX
  iconv -t ascii//TRANSLIT | sed -E s/[~'^']+//g | sed -E s/[^a-zA-Z0-9]+/-/g | sed -E s/^-+\|-+$//g | tr "[:upper:]" "[:lower:]"
fi
