#!/usr/bin/env bash

is_in_git_repo() {
  git rev-parse HEAD >/dev/null 2>&1
}

is_in_git_repo || (echo "You're not in a git repo" && exit 1)

if [[ -n ${*} ]]; then
  git stash "$@"
  exit 0
fi

stash=$(
  git stash list \
    | fzf --reverse --disabled -d: \
      --preview 'git show --color=always {1}' \
    | cut -d: -f1
)

[[ -z $stash ]] && exit 1

# if a stash was selected, pop it
git stash pop "$stash"
