#!/bin/bash

set -e

is_in_git_repo() {
  git rev-parse HEAD >/dev/null 2>&1
}

is_in_git_repo || (echo "You're not in a git repo" && exit 1)

file=$(git -c color.status=always status --short |
  fzf --multi --ansi --nth 2..,.. \
    --preview '(git diff --color=always -- {-1} | sed 1,4d | bat --theme="OneHalfDark" --color=always --style=numbers)' | cut -c4- | sed 's/.* -> //')

[[ -f "$file" ]] && vim "$file"
