#!/usr/bin/env bash

# So... this is a hack to have tabnine on nvim.

# 1. Install TabNine Extension on VSCode
# 2. Install complete-tabnine
# 3. Replace the binaries downloaded from complete-tabnine w/ the VSCode
# extension

tabNineBinaryPath="/Users/odas0r/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/3.7.5/x86_64-apple-darwin/TabNine"
completionTabNinePath="$HOME/.config/nvim/plugged/completion-tabnine/binaries/TabNine_Darwin"

install "$tabNineBinaryPath" "$completionTabNinePath"
