#!/usr/bin/env bash

set -e

wallServer=$(markpath wall-server)

# Tags Explanation
# -c: path of the session
# -s: session name
# -n: window name
# -d: "detach"
# send-keys: C-m -> Enter Key

# =====================
# wallstreeters session
# =====================
#
# manage the project wallstreeters

session="wallstreeters"
if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -c "$wallServer" -s "$session" -n sql -d
tmux send-keys -t "$session" "source ~/.bashrc && vf" C-m

tmux split-window -c "$wallServer" -t "$session" -h
tmux send-keys -t "$session" "source ~/.bashrc && vf" C-m

tmux new-window -c "$wallServer" -t "$session"
# tmux split-window -c "$wallServer" -t "$session" -h

tmux select-window -t :+1 \; last-pane

# ======================================
# ES class section
# ======================================
session="fct-es"
if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -c "$(markpath es)" -s "$session" -d

# ======================================
# IA class session
# ======================================
session="fct-ia"
if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -c "$(markpath ia)" -s "$session" -d

# ======================================
# CGI class session
# ======================================
session="fct-cgi"
if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -c "$(markpath cgi)" -s "$session" -d

# ======================================
# RC class session
# ======================================
session="fct-rc"
if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -c "$(markpath rc)" -s "$session" -d

# ======================================
# Paleontology class session
# ======================================
session="paleo"
if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -c "$(markpath paleo)" -s "$session" -d

# =================
# Session to Attach
# =================
# tmux attach-session -t "wallstreeters"
