#!/usr/bin/env bash

set -e

declare yellow="\e[33m"
declare reset="\e[0m"

echo -e "\n${yellow}Initializing your work environment...${reset}\n"

# ==================================
# Wallstreeters
# ==================================

session="wallstreeters"
workspace="$HOME/github.com/wallstreeters/client"

if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -d -s "$session" -c "$workspace"

window=1
tmux rename-window -t "${session}:${window}" "neovim"
tmux send-keys -t "${session}:${window}" "nvimr-reset" C-m

window=2
tmux new-window -t "${session}:${window}" -n "server" -c "$workspace"
tmux send-keys -t "${session}:${window}" "yarn psql" C-m

tmux select-window -t :+1

# ==================================
# ahorta
# ==================================

session="ahorta"
workspace="$HOME/github.com/ahorta-labs/ahorta"

if tmux has-session -t $session &>/dev/null; then
  tmux kill-session -t "$session"
fi

tmux new-session -d -s "$session" -c "$workspace"

window=1
tmux rename-window -t "${session}:${window}" "neovim"
tmux send-keys -t "${session}:${window}" "nvimr-reset" C-m

window=2
tmux new-window -t "${session}:${window}" -n "server" -c "$workspace"
tmux send-keys -t "${session}:${window}" "yarn psql" C-m

tmux select-window -t :+1

# ==================================
# Other Configs
# ==================================

# attach to the working tmux session
# tmux attach-session -t wallstreeters
session=$(
  tmux ls |
    fzf-tmux -p 40% --multi --prompt="Your sessions > "
)
session=${session%%:*}

if [[ -z "$session" ]]; then
  echo "session cannot be empty"
  exit 1
fi

tmux attach-session -t "$session"
