#!/usr/bin/env bash

set -e

declare -r ZET="${HOME}/github.com/zet"
declare -r JOURNAL="$ZET/journal"
declare -r DAILY_TEMPLATE="$ZET/.templates/daily.tmpl.md"

currentDate=$(date +"%Y-%m-%d")

file="$JOURNAL/${currentDate}.md"

if [[ ! -f "$file" ]]; then
  # create a new journal using the `tmpl` script
  export title="# Journal Entry, ${currentDate}"
  tmpl "$DAILY_TEMPLATE" >"$file"

  # Open the daily file
  popup nvimr "$file"
else
  popup nvimr "$file"
fi
