#!/usr/bin/env bash

set -e

currentDate=$(date +"%Y-%m-%d")
file="${HOME}/zet/journal/${currentDate}.md"

if [ -f "$file" ]; then
  popup nvim "$file"
else

  # Append the daily template on the file
  tee "$file" <<EOF >/dev/null
# Journal Entry, ${currentDate}

EOF

  # Open the daily file
  popup nvim +2 "$file"
fi
