#!/usr/bin/env bash

set -e

declare -r ZET="${HOME}/github.com/zet"
declare -r JOURNAL="$ZET/journal"

currentDate=$(date +"%Y-%m-%d")

file="$JOURNAL/${currentDate}.md"

if [ -f "$file" ]; then
  popup nvim "$file"
else

  # Append the daily template on the file
  tee "$file" <<EOF >/dev/null
# Journal Entry, ${currentDate}

EOF

  # Append the daily.md
  cat "$ZET/daily.md" >>"$file"

  # Open the daily file
  popup nvim +2 "$file"
fi
