#!/usr/bin/env bash

set -eo pipefail

if [[ $# -eq 1 ]]; then
  localhost="$1"
else
  echo "usage: tunnel-random <localhost>"
  exit 1
fi

# start the tunnel using quic protoco a.k.a http/3
cloudflared tunnel --protocol quic --url "$localhost"
