#!/bin/bash

set -e

file=$(
  fzf --preview 'bat --theme='gruvbox-dark'   --color=always --style=numbers {}'
)

if [[ -f "$file" ]]; then
  if [[ "${file: -4}" =~ (.png|jpeg|gif) ]]; then
    cd "$(dirname "$file")"
    open "$(basename "$file")"
    exit 0
  else
    vim "$file"
  fi
fi
