#!/usr/bin/env bash

set -e

file=$(
  fzf --preview 'bat --theme=ansi   --color=always --style=numbers {}'
)

if [[ -f $file ]]; then
  if [[ ${file: -4} =~ (.png|jpeg|gif) ]]; then
    cd "$(dirname "$file")"
    open "$(basename "$file")"
    exit 0
  else
    # set the working directory before opening the file
    nvim-nvr -c ":cd $(pwd)" "$file"
  fi
fi
