#!/bin/bash

set -e

if [ -z "$1" ]; then
  cd "$HOME/dot/scripts"
  file=$(
    fzf --height=90% --min-height 20 --preview-window right:70% \
      --border --preview 'bat --style=numbers --color=always {}'
  )
  [ -f "$file" ] && vim "$file"
  exit 1
fi

cmd=$(command -v "$1")
if [ -n "$cmd" ]; then
  vim "$cmd"
  exit 1
else
  echo "Command not found: $1"
fi
