#!/bin/bash

set -e

if [ -z "$1" ]; then
  cd "$HOME/dot/scripts"
  file=$(fzf)
  [ -f "$file" ] && vim "$file"
  # cd - >/dev/null
  exit 1
fi

cmd=$(command -v "$1")
if [ -n "$cmd" ]; then
  vim "$cmd"
  exit 1
else
  echo "Command not found: $1"
fi
