#!/usr/bin/env bash

set -e

DOT_TMUX="$HOME/github.com/odas0r/dot/tmux"

if [[ ! -x "$(command -v tmux)" ]]; then
  echo "tmux isn't installed, skipping..." >&2
  exit 1
fi

ln -sf "$DOT_TMUX/tmux.conf" "$HOME/.tmux.conf"
